# Jekyll配置，参考：http://jekyllrb.com/docs/home/

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

# http://jekyllrb.com/docs/configuration/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
timezone: Asia/Shanghai
encoding: utf-8

# 语法高亮，For more see: http://pygments.org/
# highlighter: rouge
highlighter: pygments

# 分页设置：http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "page:num"

# 个人设置
title: theice的编程学习博客
description: theice的编程学习博客, powered by Jekyll...
url: http://theice.github.io/
author :
  name : theice
  email : lb_nhm008@126.com
  github : theice
feed: http://theice.github.io/atom.xml
